version: '3'
services:
  gost:
    image: ginuerzh/gost
    restart: always
    ports:
      - "${GOST_PORT:-17170}:17170"
    command: "-L socks5://:17170 -F kcp://proxy:8888"
    depends_on:
      - proxy
  proxy:
    image: golangboyme/multipathudp
    restart: always
    environment:
      s: "${MIDDLE_SERVERS}"